/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Theory06PerformanceRouteImport } from './routes/theory.06-performance'
import { Route as Theory05R3fInternalsRouteImport } from './routes/theory.05-r3f-internals'
import { Route as Theory04MaterialsShadersRouteImport } from './routes/theory.04-materials-shaders'
import { Route as Theory03BufferGeometryRouteImport } from './routes/theory.03-buffer-geometry'
import { Route as Theory02SceneGraphRouteImport } from './routes/theory.02-scene-graph'
import { Route as Theory01WebglFundamentalsRouteImport } from './routes/theory.01-webgl-fundamentals'
import { Route as Theory01IntroRouteImport } from './routes/theory.01-intro'
import { Route as Lesson15PostProcessingRouteImport } from './routes/lesson.15-post-processing'
import { Route as Lesson14TextRouteImport } from './routes/lesson.14-text'
import { Route as Lesson13EventsRouteImport } from './routes/lesson.13-events'
import { Route as Lesson12ParticlesRouteImport } from './routes/lesson.12-particles'
import { Route as Lesson11LoadingModelsRouteImport } from './routes/lesson.11-loading-models'
import { Route as Lesson10EnvironmentRouteImport } from './routes/lesson.10-environment'
import { Route as Lesson09ControlsRouteImport } from './routes/lesson.09-controls'
import { Route as Lesson08CamerasRouteImport } from './routes/lesson.08-cameras'
import { Route as Lesson07ShadowsRouteImport } from './routes/lesson.07-shadows'
import { Route as Lesson06LightsRouteImport } from './routes/lesson.06-lights'
import { Route as Lesson05TransformationsRouteImport } from './routes/lesson.05-transformations'
import { Route as Lesson04TexturesRouteImport } from './routes/lesson.04-textures'
import { Route as Lesson03MaterialsRouteImport } from './routes/lesson.03-materials'
import { Route as Lesson02GeometriesRouteImport } from './routes/lesson.02-geometries'
import { Route as Lesson01BasicSceneRouteImport } from './routes/lesson.01-basic-scene'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Theory06PerformanceRoute = Theory06PerformanceRouteImport.update({
  id: '/theory/06-performance',
  path: '/theory/06-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const Theory05R3fInternalsRoute = Theory05R3fInternalsRouteImport.update({
  id: '/theory/05-r3f-internals',
  path: '/theory/05-r3f-internals',
  getParentRoute: () => rootRouteImport,
} as any)
const Theory04MaterialsShadersRoute =
  Theory04MaterialsShadersRouteImport.update({
    id: '/theory/04-materials-shaders',
    path: '/theory/04-materials-shaders',
    getParentRoute: () => rootRouteImport,
  } as any)
const Theory03BufferGeometryRoute = Theory03BufferGeometryRouteImport.update({
  id: '/theory/03-buffer-geometry',
  path: '/theory/03-buffer-geometry',
  getParentRoute: () => rootRouteImport,
} as any)
const Theory02SceneGraphRoute = Theory02SceneGraphRouteImport.update({
  id: '/theory/02-scene-graph',
  path: '/theory/02-scene-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const Theory01WebglFundamentalsRoute =
  Theory01WebglFundamentalsRouteImport.update({
    id: '/theory/01-webgl-fundamentals',
    path: '/theory/01-webgl-fundamentals',
    getParentRoute: () => rootRouteImport,
  } as any)
const Theory01IntroRoute = Theory01IntroRouteImport.update({
  id: '/theory/01-intro',
  path: '/theory/01-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson15PostProcessingRoute = Lesson15PostProcessingRouteImport.update({
  id: '/lesson/15-post-processing',
  path: '/lesson/15-post-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson14TextRoute = Lesson14TextRouteImport.update({
  id: '/lesson/14-text',
  path: '/lesson/14-text',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson13EventsRoute = Lesson13EventsRouteImport.update({
  id: '/lesson/13-events',
  path: '/lesson/13-events',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson12ParticlesRoute = Lesson12ParticlesRouteImport.update({
  id: '/lesson/12-particles',
  path: '/lesson/12-particles',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson11LoadingModelsRoute = Lesson11LoadingModelsRouteImport.update({
  id: '/lesson/11-loading-models',
  path: '/lesson/11-loading-models',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson10EnvironmentRoute = Lesson10EnvironmentRouteImport.update({
  id: '/lesson/10-environment',
  path: '/lesson/10-environment',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson09ControlsRoute = Lesson09ControlsRouteImport.update({
  id: '/lesson/09-controls',
  path: '/lesson/09-controls',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson08CamerasRoute = Lesson08CamerasRouteImport.update({
  id: '/lesson/08-cameras',
  path: '/lesson/08-cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson07ShadowsRoute = Lesson07ShadowsRouteImport.update({
  id: '/lesson/07-shadows',
  path: '/lesson/07-shadows',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson06LightsRoute = Lesson06LightsRouteImport.update({
  id: '/lesson/06-lights',
  path: '/lesson/06-lights',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson05TransformationsRoute = Lesson05TransformationsRouteImport.update({
  id: '/lesson/05-transformations',
  path: '/lesson/05-transformations',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson04TexturesRoute = Lesson04TexturesRouteImport.update({
  id: '/lesson/04-textures',
  path: '/lesson/04-textures',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson03MaterialsRoute = Lesson03MaterialsRouteImport.update({
  id: '/lesson/03-materials',
  path: '/lesson/03-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson02GeometriesRoute = Lesson02GeometriesRouteImport.update({
  id: '/lesson/02-geometries',
  path: '/lesson/02-geometries',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson01BasicSceneRoute = Lesson01BasicSceneRouteImport.update({
  id: '/lesson/01-basic-scene',
  path: '/lesson/01-basic-scene',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/lesson/01-basic-scene': typeof Lesson01BasicSceneRoute
  '/lesson/02-geometries': typeof Lesson02GeometriesRoute
  '/lesson/03-materials': typeof Lesson03MaterialsRoute
  '/lesson/04-textures': typeof Lesson04TexturesRoute
  '/lesson/05-transformations': typeof Lesson05TransformationsRoute
  '/lesson/06-lights': typeof Lesson06LightsRoute
  '/lesson/07-shadows': typeof Lesson07ShadowsRoute
  '/lesson/08-cameras': typeof Lesson08CamerasRoute
  '/lesson/09-controls': typeof Lesson09ControlsRoute
  '/lesson/10-environment': typeof Lesson10EnvironmentRoute
  '/lesson/11-loading-models': typeof Lesson11LoadingModelsRoute
  '/lesson/12-particles': typeof Lesson12ParticlesRoute
  '/lesson/13-events': typeof Lesson13EventsRoute
  '/lesson/14-text': typeof Lesson14TextRoute
  '/lesson/15-post-processing': typeof Lesson15PostProcessingRoute
  '/theory/01-intro': typeof Theory01IntroRoute
  '/theory/01-webgl-fundamentals': typeof Theory01WebglFundamentalsRoute
  '/theory/02-scene-graph': typeof Theory02SceneGraphRoute
  '/theory/03-buffer-geometry': typeof Theory03BufferGeometryRoute
  '/theory/04-materials-shaders': typeof Theory04MaterialsShadersRoute
  '/theory/05-r3f-internals': typeof Theory05R3fInternalsRoute
  '/theory/06-performance': typeof Theory06PerformanceRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/lesson/01-basic-scene': typeof Lesson01BasicSceneRoute
  '/lesson/02-geometries': typeof Lesson02GeometriesRoute
  '/lesson/03-materials': typeof Lesson03MaterialsRoute
  '/lesson/04-textures': typeof Lesson04TexturesRoute
  '/lesson/05-transformations': typeof Lesson05TransformationsRoute
  '/lesson/06-lights': typeof Lesson06LightsRoute
  '/lesson/07-shadows': typeof Lesson07ShadowsRoute
  '/lesson/08-cameras': typeof Lesson08CamerasRoute
  '/lesson/09-controls': typeof Lesson09ControlsRoute
  '/lesson/10-environment': typeof Lesson10EnvironmentRoute
  '/lesson/11-loading-models': typeof Lesson11LoadingModelsRoute
  '/lesson/12-particles': typeof Lesson12ParticlesRoute
  '/lesson/13-events': typeof Lesson13EventsRoute
  '/lesson/14-text': typeof Lesson14TextRoute
  '/lesson/15-post-processing': typeof Lesson15PostProcessingRoute
  '/theory/01-intro': typeof Theory01IntroRoute
  '/theory/01-webgl-fundamentals': typeof Theory01WebglFundamentalsRoute
  '/theory/02-scene-graph': typeof Theory02SceneGraphRoute
  '/theory/03-buffer-geometry': typeof Theory03BufferGeometryRoute
  '/theory/04-materials-shaders': typeof Theory04MaterialsShadersRoute
  '/theory/05-r3f-internals': typeof Theory05R3fInternalsRoute
  '/theory/06-performance': typeof Theory06PerformanceRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/lesson/01-basic-scene': typeof Lesson01BasicSceneRoute
  '/lesson/02-geometries': typeof Lesson02GeometriesRoute
  '/lesson/03-materials': typeof Lesson03MaterialsRoute
  '/lesson/04-textures': typeof Lesson04TexturesRoute
  '/lesson/05-transformations': typeof Lesson05TransformationsRoute
  '/lesson/06-lights': typeof Lesson06LightsRoute
  '/lesson/07-shadows': typeof Lesson07ShadowsRoute
  '/lesson/08-cameras': typeof Lesson08CamerasRoute
  '/lesson/09-controls': typeof Lesson09ControlsRoute
  '/lesson/10-environment': typeof Lesson10EnvironmentRoute
  '/lesson/11-loading-models': typeof Lesson11LoadingModelsRoute
  '/lesson/12-particles': typeof Lesson12ParticlesRoute
  '/lesson/13-events': typeof Lesson13EventsRoute
  '/lesson/14-text': typeof Lesson14TextRoute
  '/lesson/15-post-processing': typeof Lesson15PostProcessingRoute
  '/theory/01-intro': typeof Theory01IntroRoute
  '/theory/01-webgl-fundamentals': typeof Theory01WebglFundamentalsRoute
  '/theory/02-scene-graph': typeof Theory02SceneGraphRoute
  '/theory/03-buffer-geometry': typeof Theory03BufferGeometryRoute
  '/theory/04-materials-shaders': typeof Theory04MaterialsShadersRoute
  '/theory/05-r3f-internals': typeof Theory05R3fInternalsRoute
  '/theory/06-performance': typeof Theory06PerformanceRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/redirect'
    | '/lesson/01-basic-scene'
    | '/lesson/02-geometries'
    | '/lesson/03-materials'
    | '/lesson/04-textures'
    | '/lesson/05-transformations'
    | '/lesson/06-lights'
    | '/lesson/07-shadows'
    | '/lesson/08-cameras'
    | '/lesson/09-controls'
    | '/lesson/10-environment'
    | '/lesson/11-loading-models'
    | '/lesson/12-particles'
    | '/lesson/13-events'
    | '/lesson/14-text'
    | '/lesson/15-post-processing'
    | '/theory/01-intro'
    | '/theory/01-webgl-fundamentals'
    | '/theory/02-scene-graph'
    | '/theory/03-buffer-geometry'
    | '/theory/04-materials-shaders'
    | '/theory/05-r3f-internals'
    | '/theory/06-performance'
    | '/route-a'
    | '/route-b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/redirect'
    | '/lesson/01-basic-scene'
    | '/lesson/02-geometries'
    | '/lesson/03-materials'
    | '/lesson/04-textures'
    | '/lesson/05-transformations'
    | '/lesson/06-lights'
    | '/lesson/07-shadows'
    | '/lesson/08-cameras'
    | '/lesson/09-controls'
    | '/lesson/10-environment'
    | '/lesson/11-loading-models'
    | '/lesson/12-particles'
    | '/lesson/13-events'
    | '/lesson/14-text'
    | '/lesson/15-post-processing'
    | '/theory/01-intro'
    | '/theory/01-webgl-fundamentals'
    | '/theory/02-scene-graph'
    | '/theory/03-buffer-geometry'
    | '/theory/04-materials-shaders'
    | '/theory/05-r3f-internals'
    | '/theory/06-performance'
    | '/route-a'
    | '/route-b'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/customScript.js'
    | '/deferred'
    | '/redirect'
    | '/_pathlessLayout/_nested-layout'
    | '/lesson/01-basic-scene'
    | '/lesson/02-geometries'
    | '/lesson/03-materials'
    | '/lesson/04-textures'
    | '/lesson/05-transformations'
    | '/lesson/06-lights'
    | '/lesson/07-shadows'
    | '/lesson/08-cameras'
    | '/lesson/09-controls'
    | '/lesson/10-environment'
    | '/lesson/11-loading-models'
    | '/lesson/12-particles'
    | '/lesson/13-events'
    | '/lesson/14-text'
    | '/lesson/15-post-processing'
    | '/theory/01-intro'
    | '/theory/01-webgl-fundamentals'
    | '/theory/02-scene-graph'
    | '/theory/03-buffer-geometry'
    | '/theory/04-materials-shaders'
    | '/theory/05-r3f-internals'
    | '/theory/06-performance'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  RedirectRoute: typeof RedirectRoute
  Lesson01BasicSceneRoute: typeof Lesson01BasicSceneRoute
  Lesson02GeometriesRoute: typeof Lesson02GeometriesRoute
  Lesson03MaterialsRoute: typeof Lesson03MaterialsRoute
  Lesson04TexturesRoute: typeof Lesson04TexturesRoute
  Lesson05TransformationsRoute: typeof Lesson05TransformationsRoute
  Lesson06LightsRoute: typeof Lesson06LightsRoute
  Lesson07ShadowsRoute: typeof Lesson07ShadowsRoute
  Lesson08CamerasRoute: typeof Lesson08CamerasRoute
  Lesson09ControlsRoute: typeof Lesson09ControlsRoute
  Lesson10EnvironmentRoute: typeof Lesson10EnvironmentRoute
  Lesson11LoadingModelsRoute: typeof Lesson11LoadingModelsRoute
  Lesson12ParticlesRoute: typeof Lesson12ParticlesRoute
  Lesson13EventsRoute: typeof Lesson13EventsRoute
  Lesson14TextRoute: typeof Lesson14TextRoute
  Lesson15PostProcessingRoute: typeof Lesson15PostProcessingRoute
  Theory01IntroRoute: typeof Theory01IntroRoute
  Theory01WebglFundamentalsRoute: typeof Theory01WebglFundamentalsRoute
  Theory02SceneGraphRoute: typeof Theory02SceneGraphRoute
  Theory03BufferGeometryRoute: typeof Theory03BufferGeometryRoute
  Theory04MaterialsShadersRoute: typeof Theory04MaterialsShadersRoute
  Theory05R3fInternalsRoute: typeof Theory05R3fInternalsRoute
  Theory06PerformanceRoute: typeof Theory06PerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/06-performance': {
      id: '/theory/06-performance'
      path: '/theory/06-performance'
      fullPath: '/theory/06-performance'
      preLoaderRoute: typeof Theory06PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/05-r3f-internals': {
      id: '/theory/05-r3f-internals'
      path: '/theory/05-r3f-internals'
      fullPath: '/theory/05-r3f-internals'
      preLoaderRoute: typeof Theory05R3fInternalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/04-materials-shaders': {
      id: '/theory/04-materials-shaders'
      path: '/theory/04-materials-shaders'
      fullPath: '/theory/04-materials-shaders'
      preLoaderRoute: typeof Theory04MaterialsShadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/03-buffer-geometry': {
      id: '/theory/03-buffer-geometry'
      path: '/theory/03-buffer-geometry'
      fullPath: '/theory/03-buffer-geometry'
      preLoaderRoute: typeof Theory03BufferGeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/02-scene-graph': {
      id: '/theory/02-scene-graph'
      path: '/theory/02-scene-graph'
      fullPath: '/theory/02-scene-graph'
      preLoaderRoute: typeof Theory02SceneGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/01-webgl-fundamentals': {
      id: '/theory/01-webgl-fundamentals'
      path: '/theory/01-webgl-fundamentals'
      fullPath: '/theory/01-webgl-fundamentals'
      preLoaderRoute: typeof Theory01WebglFundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/01-intro': {
      id: '/theory/01-intro'
      path: '/theory/01-intro'
      fullPath: '/theory/01-intro'
      preLoaderRoute: typeof Theory01IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/15-post-processing': {
      id: '/lesson/15-post-processing'
      path: '/lesson/15-post-processing'
      fullPath: '/lesson/15-post-processing'
      preLoaderRoute: typeof Lesson15PostProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/14-text': {
      id: '/lesson/14-text'
      path: '/lesson/14-text'
      fullPath: '/lesson/14-text'
      preLoaderRoute: typeof Lesson14TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/13-events': {
      id: '/lesson/13-events'
      path: '/lesson/13-events'
      fullPath: '/lesson/13-events'
      preLoaderRoute: typeof Lesson13EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/12-particles': {
      id: '/lesson/12-particles'
      path: '/lesson/12-particles'
      fullPath: '/lesson/12-particles'
      preLoaderRoute: typeof Lesson12ParticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/11-loading-models': {
      id: '/lesson/11-loading-models'
      path: '/lesson/11-loading-models'
      fullPath: '/lesson/11-loading-models'
      preLoaderRoute: typeof Lesson11LoadingModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/10-environment': {
      id: '/lesson/10-environment'
      path: '/lesson/10-environment'
      fullPath: '/lesson/10-environment'
      preLoaderRoute: typeof Lesson10EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/09-controls': {
      id: '/lesson/09-controls'
      path: '/lesson/09-controls'
      fullPath: '/lesson/09-controls'
      preLoaderRoute: typeof Lesson09ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/08-cameras': {
      id: '/lesson/08-cameras'
      path: '/lesson/08-cameras'
      fullPath: '/lesson/08-cameras'
      preLoaderRoute: typeof Lesson08CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/07-shadows': {
      id: '/lesson/07-shadows'
      path: '/lesson/07-shadows'
      fullPath: '/lesson/07-shadows'
      preLoaderRoute: typeof Lesson07ShadowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/06-lights': {
      id: '/lesson/06-lights'
      path: '/lesson/06-lights'
      fullPath: '/lesson/06-lights'
      preLoaderRoute: typeof Lesson06LightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/05-transformations': {
      id: '/lesson/05-transformations'
      path: '/lesson/05-transformations'
      fullPath: '/lesson/05-transformations'
      preLoaderRoute: typeof Lesson05TransformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/04-textures': {
      id: '/lesson/04-textures'
      path: '/lesson/04-textures'
      fullPath: '/lesson/04-textures'
      preLoaderRoute: typeof Lesson04TexturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/03-materials': {
      id: '/lesson/03-materials'
      path: '/lesson/03-materials'
      fullPath: '/lesson/03-materials'
      preLoaderRoute: typeof Lesson03MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/02-geometries': {
      id: '/lesson/02-geometries'
      path: '/lesson/02-geometries'
      fullPath: '/lesson/02-geometries'
      preLoaderRoute: typeof Lesson02GeometriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/01-basic-scene': {
      id: '/lesson/01-basic-scene'
      path: '/lesson/01-basic-scene'
      fullPath: '/lesson/01-basic-scene'
      preLoaderRoute: typeof Lesson01BasicSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  RedirectRoute: RedirectRoute,
  Lesson01BasicSceneRoute: Lesson01BasicSceneRoute,
  Lesson02GeometriesRoute: Lesson02GeometriesRoute,
  Lesson03MaterialsRoute: Lesson03MaterialsRoute,
  Lesson04TexturesRoute: Lesson04TexturesRoute,
  Lesson05TransformationsRoute: Lesson05TransformationsRoute,
  Lesson06LightsRoute: Lesson06LightsRoute,
  Lesson07ShadowsRoute: Lesson07ShadowsRoute,
  Lesson08CamerasRoute: Lesson08CamerasRoute,
  Lesson09ControlsRoute: Lesson09ControlsRoute,
  Lesson10EnvironmentRoute: Lesson10EnvironmentRoute,
  Lesson11LoadingModelsRoute: Lesson11LoadingModelsRoute,
  Lesson12ParticlesRoute: Lesson12ParticlesRoute,
  Lesson13EventsRoute: Lesson13EventsRoute,
  Lesson14TextRoute: Lesson14TextRoute,
  Lesson15PostProcessingRoute: Lesson15PostProcessingRoute,
  Theory01IntroRoute: Theory01IntroRoute,
  Theory01WebglFundamentalsRoute: Theory01WebglFundamentalsRoute,
  Theory02SceneGraphRoute: Theory02SceneGraphRoute,
  Theory03BufferGeometryRoute: Theory03BufferGeometryRoute,
  Theory04MaterialsShadersRoute: Theory04MaterialsShadersRoute,
  Theory05R3fInternalsRoute: Theory05R3fInternalsRoute,
  Theory06PerformanceRoute: Theory06PerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
